# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxCocoa-Tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxCocoa-Tutorial
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
    pod 'RxDataSources', '~> 5.0'

end
